[[bindings]]
key = "l"
command = "open /Applications/FireFox.app"
mods = ["option"]

[[bindings]]
key = "g"
command = "open /System/Applications/Messages.app"
mods = ["option"]

[[bindings]]
key = "a"
command = "open /Applications/Alacritty.app"
mods = ["option"]

[[bindings]]
key = "s"
command = "open /Applications/Spotify.app"
mods = ["option"]

[[bindings]]
key = "k"
command = "open /Applications/KeePassXC.app"
mods = ["option", "shift"]
